import json
import csv
import io
from typing import Dict, Any
from fpdf import FPDF

class ExportService:
    def export_json(self, data: Dict[str, Any]) -> str:
        return json.dumps(data, indent=2, default=str)

    def export_csv(self, data: Dict[str, Any]) -> str:
        output = io.StringIO()
        writer = csv.writer(output)
        
        writer.writerow(["Metric / Field", "Value"])
        writer.writerow(["Prediction", data.get("prediction", "")])
        writer.writerow(["Confidence (%)", data.get("confidence", "")])
        writer.writerow(["Fake Probability (%)", data.get("fake_probability", "")])
        writer.writerow(["Real Probability (%)", data.get("real_probability", "")])
        writer.writerow(["Bias Score", data.get("bias_score", "")])
        writer.writerow(["Emotion Score", data.get("emotion_score", "")])
        writer.writerow(["Propaganda Score", data.get("propaganda_score", "")])
        writer.writerow(["Trust Score", data.get("trust_score", "")])
        writer.writerow(["Clickbait Score", data.get("clickbait_score", "")])
        
        llm = data.get("llm_analysis", {})
        if isinstance(llm, dict):
            writer.writerow(["Summary", llm.get("summary", "")])
            writer.writerow(["Political Bias", llm.get("political_bias", "")])
            writer.writerow(["Emotional Bias", llm.get("emotional_bias", "")])
            writer.writerow(["Propaganda Risk", llm.get("propaganda_detection", "")])

        return output.getvalue()

    def export_pdf(self, data: Dict[str, Any]) -> bytes:
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(30, 41, 59) # Slate 800
        pdf.cell(0, 10, "AI Fake News Detection Report", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 8, "Generated by AI Fake News Detection Platform", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(5)

        # Verdict Section
        pdf.set_font("Helvetica", "B", 14)
        verdict = data.get("prediction", "UNKNOWN")
        conf = data.get("confidence", 0)
        
        if verdict == "FAKE":
            pdf.set_text_color(225, 29, 72) # Red
        else:
            pdf.set_text_color(16, 185, 129) # Green
            
        pdf.cell(0, 10, f"VERDICT: {verdict} (Confidence: {conf}%)", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        # Risk Metrics Table
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 8, "Key Risk Scores:", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(90, 7, f"Fake Probability: {data.get('fake_probability')}%", border=1)
        pdf.cell(90, 7, f"Real Probability: {data.get('real_probability')}%", border=1, new_x="LMARGIN", new_y="NEXT")
        pdf.cell(90, 7, f"Bias Score: {data.get('bias_score')}/100", border=1)
        pdf.cell(90, 7, f"Emotion Score: {data.get('emotion_score')}/100", border=1, new_x="LMARGIN", new_y="NEXT")
        pdf.cell(90, 7, f"Propaganda Score: {data.get('propaganda_score')}/100", border=1)
        pdf.cell(90, 7, f"Trust Score: {data.get('trust_score')}/100", border=1, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(6)

        # LLM Summary & Explanation
        llm = data.get("llm_analysis", {})
        if isinstance(llm, dict):
            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 8, "Executive AI Summary:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, llm.get("summary", "N/A"))
            pdf.ln(4)

            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 8, "AI Reasoning & Analysis:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, llm.get("explanation", "N/A"))
            pdf.ln(4)

            reasons = llm.get("reasons", [])
            if reasons:
                pdf.set_font("Helvetica", "B", 11)
                pdf.cell(0, 8, "Key Indicators Flagged:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 10)
                for r in reasons:
                    pdf.cell(0, 6, f"- {r}", new_x="LMARGIN", new_y="NEXT")
                pdf.ln(4)

        # Input snippet
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Input Article Excerpt:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "I", 9)
        excerpt = data.get("original_input", "")[:500] + "..." if len(data.get("original_input", "")) > 500 else data.get("original_input", "")
        pdf.multi_cell(0, 5, excerpt)

        return pdf.output()

export_service = ExportService()
